import { ToolNTech } from "@types";

export const tools: ToolNTech[] = [
  { icon: "javascript", technology: "Javascript" },
  { icon: "html", technology: "HTML" },
  { icon: "css", technology: "CSS" },
  { icon: "react", technology: "React JS" },
  { icon: "nextjs", technology: "Next JS" },
  { icon: "tailwindCss", technology: "Tailwind CSS" },
  { icon: "scss", technology: "SCSS" },
  { icon: "bootstrap", technology: "Bootstrap" },
  { icon: "typescript", technology: "Typescript" },
  { icon: "jquery", technology: "JQuery" },
  { icon: "git", technology: "Git" },
  { icon: "redux", technology: "Redux" },
  { icon: "nodejs", technology: "Node JS" },
  { icon: "express", technology: "Express JS" },
  { icon: "mongodb", technology: "Mongo DB" },
  { icon: "supabase", technology: "Supabase" },
  { icon: "firebase", technology: "Firebase" },
  { icon: "framerMotion", technology: "Framer Motion" },
  { icon: "materialUI", technology: "Material UI" },
  { icon: "figma", technology: "Figma" },
  { icon: "styledComponents", technology: "Styled Components" },
  { icon: "gulp", technology: "Gulp JS" },
];
